### ISSUE TITLE
Bring back Firebase hosting to its former glory.

### ISSUE THREAD

**Issue by krishnabose02** [BlueBreakingBugs/Bukie#1]
Firebase hosting presently is supposed to do 2 things.
1. Host a static privacy policy page for our app (to avoid Dinesh CEO issue)
2. Redirect to a certain page containing the app download link from play store for any routes https://booksapp-e588d.firebaseapp.com/ads/{adid}.

previously hosting was optimised for the second feature only, but the newest update broke it up.

**Comment by krishnabose02** [comment]
issue has a solution here, [here](https://www.github.com/bluebreakingbugs/bukie_hosting) this has all things we already need, just add the static HTML page to the public folder will solve it.

**Comment by Ankan07** [comment]
Done!
