### ISSUE TITLE
Edit profile does not show correct name

### ISSUE THREAD

**Issue by meooow25** [BlueBreakingBugs/Bukie#21]
Registered through Google sign in, edit profile shows Google user name instead of chosen app user name.

![screenshot](https://user-images.githubusercontent.com/13716304/45933246-bfe91500-bfa6-11e8-95ec-946721a8f090.png)

**Comment by krishnabose02** [comment]
Issue has been taken care off.
https://github.com/BlueBreakingBugs/Bukie/commit/ebade46fa98629d5fb5919b5061d145507ae9cef

**Comment by krishnabose02** [comment]
Issue has been taken care off.
ebade46
