### ISSUE TITLE
Take photo option does not work in Post an Ad

### ISSUE THREAD

**Issue by meooow25** [BlueBreakingBugs/Bukie#23]
Take photo does not work for both cover and extra images.

First time:
1. App asks for media access.
2. App crashes.
3. App asks for camera access.

On future attempts:
1. Camera opens and image is taken.
2. Image does not appear on post an ad screen.

**Comment by krishnabose02** [comment]
Issue cannot be reproduced on test device. Closing this issue due to lack of clarity. Please pull the latest commit and check if issue persists, please open a new issue with possible log data.

**Comment by meooow25** [comment]
Video capture:

First time: [Google Drive link](https://drive.google.com/open?id=1OYfXRcLhMOKb8TIzHr_645hDCxqQ_voK)
Consecutive attempts: [Google Drive link](https://drive.google.com/open?id=1fbLPw4m7jws9wtooZZCQjq-urMOHpVha)

Unable to share logs from PostNewAdActivity at the moment because a) there is hardly any logging and b) someone thought it's a good idea to use different random tags in the same activity.
Will update soon. Meanwhile I suggest reopening the issue.

**Comment by krishnabose02** [comment]
The permissions flow had some slight inconsistencies and has been remodelled, and apparently doesn't cause crash. Please pull the latest changes and try again.

**Comment by meooow25** [comment]
The permissions flow has been fixed and the first time crash does not happen anymore.  
However the image still does not appear after the photo is captured. Behaviour remains identical to the second video above.

**Comment by krishnabose02** [comment]
i choose to not see this anymore ;-;

**Comment by meooow25** [comment]
Fixed ツ
