### ISSUE TITLE
check if all components of postnewad and editad working or not

### ISSUE THREAD

**Issue by indracs97** [BlueBreakingBugs/Bukie#7]
All features of postnewad and edit ad isn't working
Make interests section in rtdb and make a hardcoded category arraylist and change the category field from textview to dropdown menu
add location of user in postnewad and make it mandatory 
Solution:Just make a button as pick location and use startactivity for result to start map activity and use intents to get the geopoints in postnewad

**Comment by krishnabose02** [comment]
postnewad should have a final confirmation before uploading the ad. (a popup/dialog box showing a preview of his ad)

**Comment by krishnabose02** [comment]
![screenshot_20180916-040658](https://user-images.githubusercontent.com/24680905/45591153-55f9bb80-b967-11e8-948b-043f6ef36110.png)
![screenshot_20180916-040341](https://user-images.githubusercontent.com/24680905/45591154-55f9bb80-b967-11e8-94d9-d2a9cb975f31.png)

**Comment by indracs97** [comment]
Did you comment out any code?
Coz it's working in my mobile

**Comment by krishnabose02** [comment]
I fixed it. Should not cause errors again. And I'm closing this issue here and opening a new one. This thread is old.
